import type { SessionStats, TraceEvent } from './types.js'
import { fmtCost, fmtDuration, timeline } from './analyze.js'

/**
 * Self-contained HTML report — one file, inline CSS/JS, no CDN, works offline.
 * Open it in a browser and you see the session: cost cards, token bar per
 * model, tool histogram, error/dangling flags, full timeline.
 */

function esc(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;')
}

export function renderHtml(events: TraceEvent[], stats: SessionStats, title = 'agent session'): string {
  const cards = [
    ['LLM calls', String(stats.llmCalls)],
    ['Tool calls', String(stats.toolCalls)],
    ['Tokens in/out', `${fmtK(stats.tokensIn)} / ${fmtK(stats.tokensOut)}`],
    ['Est. cost', fmtCost(stats.estimatedCostUsd)],
    ['Wall clock', fmtDuration(stats.wallClockMs)],
    ['Errors / dangling', `${stats.errors} / ${stats.dangling}`],
  ]
    .map(([k, v]) => `<div class="card"><div class="k">${esc(k ?? '')}</div><div class="v">${esc(v ?? '')}</div></div>`)
    .join('\n      ')

  const models = Object.entries(stats.byModel)
  const maxTok = Math.max(1, ...models.map(([, m]) => m.tokensIn + m.tokensOut))
  const modelRows = models
    .map(([name, m]) => {
      const w = ((m.tokensIn + m.tokensOut) / maxTok) * 100
      return `<div class="bar-row"><div class="bar-label">${esc(name)} <span class="dim">(${m.calls} calls)</span></div>
<div class="bar"><div class="bar-in" style="width:${((m.tokensIn / maxTok) * 100).toFixed(1)}%"></div><div class="bar-out" style="width:${((m.tokensOut / maxTok) * 100).toFixed(1)}%;left:${((m.tokensIn / maxTok) * 100).toFixed(1)}%"></div></div>
<div class="dim">${fmtK(m.tokensIn)} in · ${fmtK(m.tokensOut)} out</div></div>`
    })
    .join('\n') || '<p class="dim">no llm_call events with usage</p>'

  const tools = Object.entries(stats.byTool).sort((a, b) => b[1] - a[1])
  const toolRows = tools
    .map(([name, n]) => `<tr><td>${esc(name)}</td><td class="num">${n}</td></tr>`)
    .join('\n') || '<tr><td colspan="2" class="dim">no tool calls</td></tr>'

  const slowest = stats.slowest
    .map((s) => `<tr><td>${esc(s.label)}</td><td class="num">${fmtDuration(s.durationMs)}</td></tr>`)
    .join('\n') || ''

  const tl = timeline(events, 400)
    .map((l) => `<div class="tl-line">${esc(l)}</div>`)
    .join('\n')

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>${esc(title)} — agent-trace</title>
<style>
  :root { --bg:#0d1117; --panel:#161b22; --border:#30363d; --text:#e6edf3; --dim:#8b949e;
          --in:#58a6ff; --out:#3fb950; --warn:#f0883e; --err:#f85149; }
  * { box-sizing:border-box; }
  body { margin:0; background:var(--bg); color:var(--text); font:14px/1.5 ui-monospace,SFMono-Regular,Menlo,Consolas,monospace; padding:24px; }
  h1 { font-size:18px; margin:0 0 4px; }
  .sub { color:var(--dim); margin-bottom:20px; }
  .cards { display:grid; grid-template-columns:repeat(auto-fit,minmax(150px,1fr)); gap:10px; margin-bottom:24px; }
  .card { background:var(--panel); border:1px solid var(--border); border-radius:8px; padding:12px; }
  .card .k { color:var(--dim); font-size:12px; }
  .card .v { font-size:20px; margin-top:4px; }
  h2 { font-size:14px; color:var(--dim); text-transform:uppercase; letter-spacing:.08em; margin:24px 0 8px; }
  .panel { background:var(--panel); border:1px solid var(--border); border-radius:8px; padding:14px; }
  .bar-row { margin-bottom:12px; }
  .bar-label { margin-bottom:4px; }
  .bar { position:relative; height:14px; background:#21262d; border-radius:4px; overflow:hidden; margin-bottom:2px; }
  .bar-in { position:absolute; top:0; bottom:0; left:0; background:var(--in); }
  .bar-out { position:absolute; top:0; bottom:0; background:var(--out); opacity:.85; }
  table { width:100%; border-collapse:collapse; }
  td { padding:4px 8px; border-bottom:1px solid var(--border); }
  .num { text-align:right; }
  .dim { color:var(--dim); }
  .tl-line { white-space:pre; padding:1px 0; }
  .cols { display:grid; grid-template-columns:1fr 1fr; gap:14px; }
  @media (max-width:800px){ .cols{grid-template-columns:1fr;} }
</style>
</head>
<body>
  <h1>${esc(title)}</h1>
  <div class="sub">generated by agent-trace · ${new Date().toISOString()}</div>

  <div class="cards">
      ${cards}
  </div>

  <h2>Tokens by model</h2>
  <div class="panel">${modelRows}</div>

  <div class="cols">
    <div>
      <h2>Tool usage</h2>
      <div class="panel"><table>${toolRows}</table></div>
    </div>
    <div>
      <h2>Slowest calls</h2>
      <div class="panel"><table>${slowest || '<tr><td class="dim">no duration data</td></tr>'}</table></div>
    </div>
  </div>

  <h2>Timeline</h2>
  <div class="panel">${tl}</div>
</body>
</html>`
}

function fmtK(n: number): string {
  return n >= 1000 ? `${(n / 1000).toFixed(1)}k` : String(n)
}
